"""rname Type.user_type and Status.status to *name respvly

Revision ID: 0b8e3b13fb22
Revises: 6429a31bdd37
Create Date: 2021-03-04 20:05:35.097221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8e3b13fb22'
down_revision = '6429a31bdd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_index('ix_election_name_of_election')
        batch_op.create_index(batch_op.f('ix_election_name'), ['name'], unique=False)
        batch_op.drop_column('name_of_election')

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('status')

    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('name')

    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_of_election', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_election_name'))
        batch_op.create_index('ix_election_name_of_election', ['name_of_election'], unique=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
