"""add ending_at and add starting_at to Electiono

Revision ID: 531ca9346f5f
Revises: eaed9dd69d3d
Create Date: 2021-03-07 19:32:24.441900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531ca9346f5f'
down_revision = 'eaed9dd69d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starting_at', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_election_date_of_election')
        batch_op.drop_index('ix_election_time_of_election')
        batch_op.create_index(batch_op.f('ix_election_starting_at'), ['starting_at'], unique=False)
        batch_op.drop_column('date_of_election')
        batch_op.drop_column('time_of_election')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_of_election', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_of_election', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_election_starting_at'))
        batch_op.create_index('ix_election_time_of_election', ['time_of_election'], unique=False)
        batch_op.create_index('ix_election_date_of_election', ['date_of_election'], unique=False)
        batch_op.drop_column('starting_at')

    # ### end Alembic commands ###
