"""add position table

Revision ID: 608e147b0ef9
Revises: bb65a9ca237d
Create Date: 2021-03-11 16:29:08.480289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608e147b0ef9'
down_revision = 'bb65a9ca237d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], name=op.f('fk_position_election_id_election'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position'))
    )
    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_title'), ['title'], unique=False)

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_candidate_election_id_election', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_candidate_position_id_position'), 'position', ['position_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('position')
        batch_op.drop_column('election_id')

    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.drop_column('slug')

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_result_election_id_election', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_result_position_id_position'), 'position', ['position_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('election_id')

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_vote_election_id_election', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_vote_position_id_position'), 'position', ['position_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('election_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_vote_position_id_position'), type_='foreignkey')
        batch_op.create_foreign_key('fk_vote_election_id_election', 'election', ['election_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('position_id')

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_result_position_id_position'), type_='foreignkey')
        batch_op.create_foreign_key('fk_result_election_id_election', 'election', ['election_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('position_id')

    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('position', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_candidate_position_id_position'), type_='foreignkey')
        batch_op.create_foreign_key('fk_candidate_election_id_election', 'election', ['election_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('position_id')

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_title'))

    op.drop_table('position')
    # ### end Alembic commands ###
