"""empty message

Revision ID: a6665ad37419
Revises: f3a0afe252e1
Create Date: 2021-03-04 01:24:28.590987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6665ad37419'
down_revision = 'f3a0afe252e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_candidate_name'), 'candidate', ['name'], unique=False)
    op.add_column('election', sa.Column('password', sa.String(), nullable=True))
    op.create_index(op.f('ix_election_name_of_election'), 'election', ['name_of_election'], unique=False)
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.create_foreign_key(None, 'election', 'user', ['owner'], ['id'])
    op.drop_column('election', 'date')
    op.drop_column('election', 'time')
    op.drop_column('election', 'user_id')
    op.drop_column('election', 'published')
    op.add_column('vote', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'password')
    op.add_column('election', sa.Column('published', sa.BOOLEAN(), nullable=True))
    op.add_column('election', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.add_column('election', sa.Column('time', sa.DATETIME(), nullable=True))
    op.add_column('election', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.create_foreign_key(None, 'election', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_election_name_of_election'), table_name='election')
    op.drop_column('election', 'password')
    op.drop_index(op.f('ix_candidate_name'), table_name='candidate')
    # ### end Alembic commands ###
