"""empty message

Revision ID: f3a0afe252e1
Revises: c846676c94c0
Create Date: 2021-03-03 23:24:00.321911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a0afe252e1'
down_revision = 'c846676c94c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.create_foreign_key(None, 'election', 'user', ['owner'], ['id'])
    op.drop_column('election', 'time')
    op.drop_column('election', 'date')
    op.drop_column('election', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('election', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.add_column('election', sa.Column('date', sa.DATETIME(), nullable=True))
    op.add_column('election', sa.Column('time', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'election', type_='foreignkey')
    op.create_foreign_key(None, 'election', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
